### ISSUE TITLE
Postmark emails not sending

### ISSUE THREAD

**Issue by ynnoj** [GraphCMS/gatsby-graphcms-ecommerce-starter#70]
The functions to send Postmark emails for order confirmation and dispatch aren't firing. Requires investigation.

**Comment by domtaylor** [comment]
I've not ben able to get Postmark to send emails either, so will be keen to see your solution. Maybe CORS issue? Use? https://www.npmjs.com/package/cors

**Comment by ynnoj** [comment]
@domtaylor I just updated this app to work with the new GraphCMS. Postmark emails are now sending.

**Comment by domtaylor** [comment]
@ynnoj awesome! thanks for letting me know.
