### ISSUE TITLE
Add Algolia

### ISSUE THREAD

**Issue by ynnoj** [GraphCMS/gatsby-graphcms-ecommerce-starter#72]

**Comment by pjsachdev** [comment]
You could also use something like MeiliSearch, which is a nice open-source self-hosted alternative to Algolia.

**Comment by ynnoj** [comment]
@pjsachdev Thanks for the recommendation!

**Comment by pjsachdev** [comment]
No worries! It is a really nice open source Algolia alternative, but it is still pretty new. You've done an amazing job with this starter, great job!

**Comment by ynnoj** [comment]
@pjsachdev Thanks for the kind words 😊
