### ISSUE TITLE
How to configure Stripe/Printful webhooks ?

### ISSUE THREAD

**Issue by Samciu** [GraphCMS/gatsby-graphcms-ecommerce-starter#87]
I have readed the docs of stripe and printful，but how to use the functions/order-created,order-dispatched to trigger the postmark？

**Comment by notrab** [comment]
Hey 👋 

You'll want to setup webhooks to look a little something like this:

<img width="843" alt="Screenshot 2020-08-29 at 16 19 16" src="https://user-images.githubusercontent.com/950181/91640160-6354c700-ea13-11ea-9c80-4efd40a0bfd0.png">

**Order created notification**
- Content model: `Order`
- Stage: `Draft`
- Action: `Create`

**Order dispatched notification**
- Content model: `Order`
- Stage: Wildcard
- Action: Wildcard

When this example was first created we were using legacy GraphCMS, so it's likely that there is some refactoring required in a real world application, but this repo should give you an idea of how all of the tools connect together 😄
