### ISSUE TITLE
TypeError: Cannot read property 'activities' of undefined

### ISSUE THREAD

**Issue by PirunSeng** [GraphCMS/gatsby-graphcms-ecommerce-starter#89]
I clone the project, ran ```yarn``` then ```cp .env.sample .env``` and put the endpoint form GraphCMS. I think this error is not something related to other environment variables if I'm not wrong.

Then I ran ```yarn dev``` to start up but got this error.

```
...\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

TypeError: Cannot read property 'activities' of undefined
```

**Comment by notrab** [comment]
Hi @PirunSeng 

Did you satisfy all of the values in the `.env` once you copied `.env.sample`?

You'll need to setup Printful, and connect products from there to GraphCMS. We understand this is far from ideal and we are in the process of simplifying the configuration for this example.

Stay tuned!

**Comment by PirunSeng** [comment]
![gatsby-graphcms](https://user-images.githubusercontent.com/12696293/99060080-1758fd80-25d2-11eb-8e0f-d4ecfa0af7af.png)

Thanks @notrab for your prompt response :)
Now I have set up two env, GRAPHCMS_ENDPOINT and PRINTFUL_API_KEY
Do I need to set all the env?
By the way, after setting PRINTFUL_API_KEY, and running ```yarn dev``` again, I get the error as above screenshot. Could you see what my problem is from there?

**Comment by notrab** [comment]
@PirunSeng you'll need to set the graphcms query env variable. I wouldn't recommend making your API public as you will expose the orders/customer details.

We're working on some improvements to this repo - please hang in there :)
